variables:
  # Release new Arkcase version
  # ============================

  # Release RC1 from develop branch (sets the develop branch new snapshot version)
  # ------------------------------------------------------------------------------
  # RELEASE_CANDIDATE_1: true
  # RELEASE_VERSION: 3.3.3-RC1
  # DEVELOP_NEW_VERSION: 3.3.4-SNAPSHOT
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)

  # Start RC2 to push commits to branch (from master branch) (**** repeat this for all additional release candididates ****)
  # ------------------------------------------------------------------------------------------------------------------------
  # START_RELEASE_CANDIDATE_X: true
  # RELEASE_VERSION: 3.3.3-RC2
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)

  # Release RC2 (merges changes to master branch. Note: hotfix commits should be merged to both the hotfix and develop branches)
  # ----------------------------------------------------------------------------------------------------------------------------
  # RELEASE_CANDIDATE_X: true
  # RELEASE_VERSION: 3.3.3-RC2
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)

  # Release final version in master (after no more release candidates are planned)
  # ------------------------------------------------------------------------------
  # RELEASE: true
  # RELEASE_VERSION: 3.3.3
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)


  # Hotfix for older Arkcase released version
  # =========================================

  # Start support branch for a released Arkcase version (creates support/3.3.2 branch which can be used for all future release fixes for 3.3.2 version)
  # ---------------------------------------------------------------------------------------------------------------------------------------------------
  # START_SUPPORT_BRANCH: true
  # RELEASE_TAG: 3.3.2
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)

  # Start hotfix for Arkcase support
  # --------------------------------
  # START_HOTFIX: true
  # HOTFIX_SUPPORT_VERSION: 3.3.2 (**** keep this version for all additional hotfixes to the same base released version ****)
  # RELEASE_VERSION: 3.3.2.1       (**** increment this version for additional hotfixes like 3.3.2.2 ****)
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)

  # Release new hotfix version
  # --------------------------
  # RELEASE_HOTFIX: true
  # HOTFIX_SUPPORT_VERSION: 3.3.2
  # RELEASE_VERSION: 3.3.2.1
  # RELEASE_ALL: true (Optional: if you want to trigger the release pipeline on all othe projects: configuration, externa-portal-ui, external-portal-backend, configuration server)
  GIT_USERNAME: 'Arkcase Build'
  GIT_USERMAIL: 'arkcase-build@armedia.com'
  GIT_URL: 'git@***REMOVED***:arkcase/ArkCase.git'


release_candidate_1:
  stage: release
  only: 
    variables:
     - $RELEASE_CANDIDATE_1
  script:
    - echo '<settings>' > /root/.m2/settings.xml
    - echo '  <servers>' >> /root/.m2/settings.xml
    - echo '    <server>' >> /root/.m2/settings.xml
    - echo '      <id>arkcase.release</id>' >> /root/.m2/settings.xml
    - echo '      <username>admin</username>' >> /root/.m2/settings.xml
    - echo "      <password>$MVN_PASSWORD</password>" >> /root/.m2/settings.xml
    - echo '    </server>' >> /root/.m2/settings.xml
    - echo '  </servers>' >> /root/.m2/settings.xml
    - echo '</settings>' >> /root/.m2/settings.xml
    - export MAVEN_OPTS="-Xmx2048M -Xss256M -XX:MetaspaceSize=2048M -XX:+CMSClassUnloadingEnabled"
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - apt-get update
    - apt-get install -y zip sshpass
    - export SSHPASS=$SSHPASS_ARKCASE
    - mvn -B gitflow:release-start -DreleaseVersion=$RELEASE_VERSION -DcommitDevelopmentVersionAtStart=true -DdevelopmentVersion=$DEVELOP_NEW_VERSION
    - mvn -B gitflow:release-finish -DskipTestProject=true -DcommitDevelopmentVersionAtStart=true
    - git checkout master
    - mvn -DskipITs -T 4 -B deploy "-DaltDeploymentRepository=arkcase.release::default::https://***REMOVED***/repository/arkcase.release/"
    - sshpass -e sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ***REMOVED*** <<< $'put acm-standard-applications/acm-law-enforcement/target/*.war /from-arkcase/arkcase-'$RELEASE_VERSION'.war' 
    # Deploy on test servers
    
start_release_candidate_X:
  stage: release
  only: 
    variables:
     - $START_RELEASE_CANDIDATE_X
  script:
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - mvn -B gitflow:hotfix-start -DpushRemote=true -DhotfixVersion=$RELEASE_VERSION

release_candidate_X:
  stage: release
  only: 
    variables:
     - $RELEASE_CANDIDATE_X
  script:
    - echo '<settings>' > /root/.m2/settings.xml
    - echo '  <servers>' >> /root/.m2/settings.xml
    - echo '    <server>' >> /root/.m2/settings.xml
    - echo '      <id>arkcase.release</id>' >> /root/.m2/settings.xml
    - echo '      <username>admin</username>' >> /root/.m2/settings.xml
    - echo "      <password>$MVN_PASSWORD</password>" >> /root/.m2/settings.xml
    - echo '    </server>' >> /root/.m2/settings.xml
    - echo '  </servers>' >> /root/.m2/settings.xml
    - echo '</settings>' >> /root/.m2/settings.xml
    - export MAVEN_OPTS="-Xmx2048M -Xss256M -XX:MetaspaceSize=2048M -XX:+CMSClassUnloadingEnabled"
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - apt-get update
    - apt-get install -y zip sshpass
    - export SSHPASS=$SSHPASS_ARKCASE
    - git checkout --track origin/hotfix/$RELEASE_VERSION
    - mvn -B gitflow:hotfix-finish -DpushRemote=true -DhotfixVersion=$RELEASE_VERSION -DskipTestProject=true -DskipMergeDevBranch=true
    - git checkout master
    - mvn -DskipITs -T 4 -B deploy "-DaltDeploymentRepository=arkcase.release::default::https://***REMOVED***/repository/arkcase.release/"
    - sshpass -e sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ***REMOVED*** <<< $'put acm-standard-applications/acm-law-enforcement/target/*.war /from-arkcase/arkcase-'$RELEASE_VERSION'.war' 
    # Deploy on test servers

release:
  stage: release
  only: 
    variables:
     - $RELEASE
  script:
    - echo '<settings>' > /root/.m2/settings.xml
    - echo '  <servers>' >> /root/.m2/settings.xml
    - echo '    <server>' >> /root/.m2/settings.xml
    - echo '      <id>arkcase.release</id>' >> /root/.m2/settings.xml
    - echo '      <username>admin</username>' >> /root/.m2/settings.xml
    - echo "      <password>$MVN_PASSWORD</password>" >> /root/.m2/settings.xml
    - echo '    </server>' >> /root/.m2/settings.xml
    - echo '  </servers>' >> /root/.m2/settings.xml
    - echo '</settings>' >> /root/.m2/settings.xml
    - export MAVEN_OPTS="-Xmx2048M -Xss256M -XX:MetaspaceSize=2048M -XX:+CMSClassUnloadingEnabled"
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - apt-get update
    - apt-get install -y zip sshpass
    - export SSHPASS=$SSHPASS_ARKCASE
    - mvn -B gitflow:hotfix-start -DhotfixVersion=$RELEASE_VERSION
    - mvn -B gitflow:hotfix-finish -DhotfixVersion=$RELEASE_VERSION -DskipTestProject=true -DskipMergeDevBranch=true
    - git checkout master
    - mvn -DskipITs -T 4 -B deploy "-DaltDeploymentRepository=arkcase.release::default::https://***REMOVED***/repository/arkcase.release/"
    - sshpass -e sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ***REMOVED*** <<< $'put acm-standard-applications/acm-law-enforcement/target/*.war /from-arkcase/arkcase-'$RELEASE_VERSION'.war' 
    # Deploy on test servers
    
start_support_branch:
  stage: release
  only: 
    variables:
     - $START_SUPPORT_BRANCH
  script:
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - mvn -B gitflow:support-start -DpushRemote=true -DtagName=$RELEASE_TAG

start_hotfix:
  stage: release
  only: 
    variables:
     - $START_HOTFIX
  script:
    - mvn -B gitflow:hotfix-start -DpushRemote=true -DhotfixVersion=$RELEASE_VERSION -DfromBranch=support/$HOTFIX_SUPPORT_VERSION

release_hotfix:
  stage: release
  only: 
    variables:
     - $RELEASE_HOTFIX
  script:
    - echo '<settings>' > /root/.m2/settings.xml
    - echo '  <servers>' >> /root/.m2/settings.xml
    - echo '    <server>' >> /root/.m2/settings.xml
    - echo '      <id>arkcase.release</id>' >> /root/.m2/settings.xml
    - echo '      <username>admin</username>' >> /root/.m2/settings.xml
    - echo "      <password>$MVN_PASSWORD</password>" >> /root/.m2/settings.xml
    - echo '    </server>' >> /root/.m2/settings.xml
    - echo '  </servers>' >> /root/.m2/settings.xml
    - echo '</settings>' >> /root/.m2/settings.xml
    - export MAVEN_OPTS="-Xmx2048M -Xss256M -XX:MetaspaceSize=2048M -XX:+CMSClassUnloadingEnabled"
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_USERMAIL"
    - git remote set-url origin "$GIT_URL"
    - apt-get update
    - apt-get install -y zip sshpass
    - export SSHPASS=$SSHPASS_ARKCASE
    - mvn -B gitflow:hotfix-finish -DpushRemote=true -DhotfixVersion=support/$HOTFIX_SUPPORT_VERSION/$RELEASE_VERSION -DskipTestProject=true -DskipMergeDevBranch=true
    - git checkout --track origin/support/$HOTFIX_SUPPORT_VERSION/$RELEASE_VERSION
    - mvn -DskipITs -T 4 -B deploy "-DaltDeploymentRepository=arkcase.release::default::https://***REMOVED***/repository/arkcase.release/"
    - sshpass -e sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ***REMOVED*** <<< $'put acm-standard-applications/acm-law-enforcement/target/*.war /from-arkcase/arkcase-'$RELEASE_VERSION'.war' 
    # Deploy on test servers

release_all:
  stage: release
  only: 
    variables:
     - $RELEASE_ALL
  script:
    # Trigger other project releases:
    # Configuration
    - curl -k --request POST --form token=$CONFIGURATION_PROJECT_TOKEN --form ref=core
      --form "variables[RELEASE_CANDIDATE_1]=$RELEASE_CANDIDATE_1"
      --form "variables[RELEASE_VERSION]=$RELEASE_VERSION"
      --form "variables[DEVELOP_NEW_VERSION]=$DEVELOP_NEW_VERSION"
      --form "variables[START_RELEASE_CANDIDATE_X]=$START_RELEASE_CANDIDATE_X"
      --form "variables[RELEASE_CANDIDATE_X]=$RELEASE_CANDIDATE_X"
      --form "variables[RELEASE]=$RELEASE"
      --form "variables[START_SUPPORT_BRANCH]=$START_SUPPORT_BRANCH"
      --form "variables[RELEASE_TAG]=$RELEASE_TAG"
      --form "variables[START_HOTFIX]=$START_HOTFIX"
      --form "variables[HOTFIX_SUPPORT_VERSION]=$HOTFIX_SUPPORT_VERSION"
      --form "variables[RELEASE_HOTFIX]=$RELEASE_HOTFIX"
      https://***REMOVED***/api/v4/projects/30/trigger/pipeline
    # Portal backend
    - curl -k --request POST --form token=$EXTERNAL_WEB_PORTAL_PROJECT_TOKEN --form ref=develop
      --form "variables[RELEASE_CANDIDATE_1]=$RELEASE_CANDIDATE_1"
      --form "variables[RELEASE_VERSION]=$RELEASE_VERSION"
      --form "variables[DEVELOP_NEW_VERSION]=$DEVELOP_NEW_VERSION"
      --form "variables[START_RELEASE_CANDIDATE_X]=$START_RELEASE_CANDIDATE_X"
      --form "variables[RELEASE_CANDIDATE_X]=$RELEASE_CANDIDATE_X"
      --form "variables[RELEASE]=$RELEASE"
      --form "variables[START_SUPPORT_BRANCH]=$START_SUPPORT_BRANCH"
      --form "variables[RELEASE_TAG]=$RELEASE_TAG"
      --form "variables[START_HOTFIX]=$START_HOTFIX"
      --form "variables[HOTFIX_SUPPORT_VERSION]=$HOTFIX_SUPPORT_VERSION"
      --form "variables[RELEASE_HOTFIX]=$RELEASE_HOTFIX"
      https://***REMOVED***/api/v4/projects/193/trigger/pipeline
    # Portal UI
    - curl -k --request POST --form token=$EXTERNAL_WEB_PORTAL_UI_PROJECT_TOKEN --form ref=develop
      --form "variables[RELEASE_CANDIDATE_1]=$RELEASE_CANDIDATE_1"
      --form "variables[RELEASE_VERSION]=$RELEASE_VERSION"
      --form "variables[DEVELOP_NEW_VERSION]=$DEVELOP_NEW_VERSION"
      --form "variables[START_RELEASE_CANDIDATE_X]=$START_RELEASE_CANDIDATE_X"
      --form "variables[RELEASE_CANDIDATE_X]=$RELEASE_CANDIDATE_X"
      --form "variables[RELEASE]=$RELEASE"
      --form "variables[START_SUPPORT_BRANCH]=$START_SUPPORT_BRANCH"
      --form "variables[RELEASE_TAG]=$RELEASE_TAG"
      --form "variables[START_HOTFIX]=$START_HOTFIX"
      --form "variables[HOTFIX_SUPPORT_VERSION]=$HOTFIX_SUPPORT_VERSION"
      --form "variables[RELEASE_HOTFIX]=$RELEASE_HOTFIX"
      https://***REMOVED***/api/v4/projects/237/trigger/pipeline
    # Config server
    - curl -k --request POST --form token=$CONFIG_SERVER_PROJECT_TOKEN --form ref=develop
      --form "variables[RELEASE_CANDIDATE_1]=$RELEASE_CANDIDATE_1"
      --form "variables[RELEASE_VERSION]=$RELEASE_VERSION"
      --form "variables[DEVELOP_NEW_VERSION]=$DEVELOP_NEW_VERSION"
      --form "variables[START_RELEASE_CANDIDATE_X]=$START_RELEASE_CANDIDATE_X"
      --form "variables[RELEASE_CANDIDATE_X]=$RELEASE_CANDIDATE_X"
      --form "variables[RELEASE]=$RELEASE"
      --form "variables[START_SUPPORT_BRANCH]=$START_SUPPORT_BRANCH"
      --form "variables[RELEASE_TAG]=$RELEASE_TAG"
      --form "variables[START_HOTFIX]=$START_HOTFIX"
      --form "variables[HOTFIX_SUPPORT_VERSION]=$HOTFIX_SUPPORT_VERSION"
      --form "variables[RELEASE_HOTFIX]=$RELEASE_HOTFIX"
      https://***REMOVED***/api/v4/projects/322/trigger/pipeline
    # Snowbound
    - curl -k --request POST --form token=$SNOWBOUND_PROJECT_TOKEN --form ref=core
      --form "variables[RELEASE_CANDIDATE_1]=$RELEASE_CANDIDATE_1"
      --form "variables[RELEASE_VERSION]=$RELEASE_VERSION"
      --form "variables[DEVELOP_NEW_VERSION]=$DEVELOP_NEW_VERSION"
      --form "variables[START_RELEASE_CANDIDATE_X]=$START_RELEASE_CANDIDATE_X"
      --form "variables[RELEASE_CANDIDATE_X]=$RELEASE_CANDIDATE_X"
      --form "variables[RELEASE]=$RELEASE"
      --form "variables[START_SUPPORT_BRANCH]=$START_SUPPORT_BRANCH"
      --form "variables[RELEASE_TAG]=$RELEASE_TAG"
      --form "variables[START_HOTFIX]=$START_HOTFIX"
      --form "variables[HOTFIX_SUPPORT_VERSION]=$HOTFIX_SUPPORT_VERSION"
      --form "variables[RELEASE_HOTFIX]=$RELEASE_HOTFIX"
      https://***REMOVED***/api/v4/projects/39/trigger/pipeline
    # Installer