package com.armedia.arkcase.uitests.cases;

import java.awt.AWTException;
import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.openqa.selenium.By;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;

import com.armedia.arkcase.uitests.base.ArkCaseAuthentication;
import com.armedia.arkcase.uitests.base.ArkCaseTestBase;
import com.armedia.arkcase.uitests.group.SmokeTests;
import com.armedia.arkcase.uitests.task.TaskPage;
import com.armedia.arkcase.uitests.task.TasksPage;

public class CaseWithTasksTests extends ArkCaseTestBase {

	CasePage casePom = PageFactory.initElements(driver, CasePage.class);
	CasesPage casesPom = PageFactory.initElements(driver, CasesPage.class);
	TasksPage tasks = PageFactory.initElements(driver, TasksPage.class);
	TaskPage task = PageFactory.initElements(driver, TaskPage.class);

	@Test
	@Category({ SmokeTests.class })
	public void createNewCaseAddTaskCloseTask() throws InterruptedException, IOException {
		// create new case add task from case page,delete the case

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("Samuel Supervisor");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		Thread.sleep(3000);
		casesPom.completeButtonInTaskPage.click();
		Thread.sleep(5000);
		Assert.assertEquals("After complete button is clicked,State of the Task is wrong", "CLOSED", casesPom.stateTask.getText());
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.caseTasks.click();
		Thread.sleep(5000);
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		casesPom.verifyTaskInTheTaskTable("CaseTask", "Samuel Supervisor", "Medium", "05/20/2016", "CLOSED");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	public void createNewCaseAddTaskAddDeleteTagDeleteCase() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(5000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.tagsLinkClick();
		tasks.verifyTagsTable();
		tasks.addNewTag("michel");
		Thread.sleep(3000);
		tasks.verifyAddedTag("michel", "Samuel Supervisor");
		tasks.refreshButton.click();
		Thread.sleep(4000);
		tasks.verifyAddedTag("michel", "Samuel Supervisor");
		tasks.deleteAddedTag();
		Thread.sleep(4000);
		tasks.refreshButton.click();
		Thread.sleep(4000);
		tasks.verifyIfTagIsDeleted();
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.caseTasks.click();
		Thread.sleep(4000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskTaskDetailsDeleteCase() throws InterruptedException, IOException, AWTException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.insertLink("ArkCase", "http://www.arkcase.com/");
		Thread.sleep(4000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.overviewLinkClick();
		tasks.detailsLinkClick();
		tasks.verifyDetailsTasksSection();
		tasks.editInsertedLInk();
		Thread.sleep(2000);
		tasks.verifyInsertedLinkDetails("ArkCase1");
		tasks.detailsSaveButtonClick();
		Thread.sleep(2000);
		tasks.clearInsertedLInk();
		Thread.sleep(3000);
		tasks.insertLink("ArkCase", "http://www.arkcase.com/");
		tasks.detailsSaveButtonClick();
		Thread.sleep(3000);
		tasks.clearInsertedLInk();
		Thread.sleep(2000);
		tasks.verifyDetailsPanelIsEmpty();
		Thread.sleep(3000);
		tasks.detailsInsertPicture();
		Thread.sleep(2000);
		tasks.detailsRemovePicture();
		Thread.sleep(3000);
		tasks.tagsLinkClick();
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskAddDeleteNoteDeleteCase() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.notestLinkClick();
		Thread.sleep(300);
		tasks.addNewNote("bug");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		tasks.verifyAddedNote("bug", "samuel-acm");
		tasks.editNote("bug2");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		tasks.verifyAddedNote("bug2", "samuel-acm");
		Thread.sleep(3000);
		tasks.deleteNote();
		Thread.sleep(3000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		tasks.verifyIfNoteIsDeleted();
		Thread.sleep(3000);
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskVerifyWorkflowTable() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.workflowLinkClick();
		Thread.sleep(3000);
		tasks.workFlowData("Samuel Supervisor");
		casesPom.completeButtonInTaskPage.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		tasks.workflowLinkClick();
		Thread.sleep(3000);
		tasks.verifyWorkflowTableStatusClosed("Samuel Supervisor");
		Thread.sleep(3000);
		tasks.notestLinkClick();
		Thread.sleep(3000);
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskVerifyHistoryTableDeleteCase() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.historyLinkClick();
		Thread.sleep(4000);
		tasks.verifyHistorySection();
		tasks.verifyHistoryTableData("Task Created", "Samuel Supervisor");
		casesPom.completeButtonInTaskPage.click();
		Thread.sleep(4000);
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAsociateTaskWithCase() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		String caseid = casesPom.caseId.getText().toString();
		task.newButtonClick();
		task.newTaskButtonClick();
		task.typeSubject("TestMilanassociate");
		task.typeStartDate("03/18/2016");
		task.selectStatusActive();
		task.typeDuedate("03/19/2016");
		Thread.sleep(2000);
		task.parentTypeDropDownClick();
		Thread.sleep(2000);
		task.asscociateWithCase();
		Thread.sleep(2000);
		task.associateInput(caseid);
		task.saveButtonClick();
		Thread.sleep(5000);
		task.caseNameClick();
		Thread.sleep(5000);
		task.casesTaskLinkClick();
		Thread.sleep(8000);
		task.verifyTaskInCasesTaskTable();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskEditInformationRibonOfTaskDeleteCase() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.editSubjectClickCncel();
		Thread.sleep(2000);
		tasks.editSubjectClickConfirm("TestMilan2");
		tasks.editPercentClickCancel();
		Thread.sleep(2000);
		tasks.editPercentClickConfirm("45");
		Thread.sleep(2000);
		tasks.editStartDateClickCancel();
		Thread.sleep(2000);
		tasks.editStartDateClickConfirm("04/06/2016");
		tasks.editDueDateClickCancel();
		Thread.sleep(2000);
		tasks.editDueDateClickConfirm("04/07/2016");
		tasks.EditPriorityCancelButton();
		tasks.priority.click();
		new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("Medium");
		tasks.priorityConfirmButton.click();
		tasks.refreshButton.click();
		Thread.sleep(3000);
		Assert.assertTrue(tasks.priority.getText().equals("Medium"));
		tasks.priority.click();
		new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("High");
		tasks.priorityConfirmButton.click();
		tasks.refreshButton.click();
		Thread.sleep(3000);
		Assert.assertTrue(tasks.priority.getText().equals("High"));
		tasks.priority.click();
		new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("Expedite");
		tasks.priorityConfirmButton.click();
		tasks.refreshButton.click();
		Thread.sleep(3000);
		Assert.assertTrue(tasks.priority.getText().equals("Expedite"));
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	public void createNewCaseAddTaskChangeAssigneeCheckButtonsAreDisplayed() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.assignee.click();
		new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("Bill Thomas");
		tasks.assigneeConfirm.click();
		Thread.sleep(2000);
		tasks.refreshButton.click();
		Assert.assertTrue(tasks.assignee.getText().equals("Bill Thomas"));
		tasks.editAssigneeCheckButtonsIfDisabled();
		Thread.sleep(2000);
		tasks.assignee.click();
		Thread.sleep(2000);
		new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("Samuel Supervisor");
		tasks.assigneeConfirm.click();
		Thread.sleep(2000);
		tasks.refreshButton.click();
		Assert.assertTrue(tasks.assignee.getText().equals("Samuel Supervisor"));
		tasks.editAssigneeCheckButtonsIfEnabled();
		Thread.sleep(2000);
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.caseTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskDeleteTaskTryToAddNote() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.completeButtonClick();
		Assert.assertEquals("Task state should be CLOSED", "CLOSED", tasks.stateTask.getText());
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		Thread.sleep(3000);
		casesPom.tableTaskTitle.click();
		Thread.sleep(10000);
		tasks.refreshButtonInTaskList.click();
		Thread.sleep(5000);
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "CLOSED");
		tasks.notestLinkClick();
		Assert.assertFalse("Add note button is enabled", tasks.addNewNoteButton.isEnabled());
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseAddTaskDeleteTaskTryToAddDocument() throws InterruptedException, IOException {

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseAddTask");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		Thread.sleep(4000);
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseAddTask", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseAddTask (DRAFT)", casesPom.caseTitleDraft.getText());
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		casesPom.taskAddButton.click();
		Thread.sleep(5000);
		task.verifyTaskTitle();
		task.verifySubjectTitleInput();
		task.verifyAssighnToLabelInput();
		task.verifyAssociateWith();
		task.verifyStartDate();
		task.verifyDueDate();
		task.verifyPriority();
		task.verifyNotes();
		task.assignTo("sam");
		task.typeSubject("CaseTask");
		task.typeDuedate("05/20/2016");
		Thread.sleep(3000);
		task.saveButtonClick();
		Thread.sleep(5000);
		casesPom.verifyCaseWIthAddedTask("Samuel Supervisor", "Background Investigation", "ACM_INVESTIGATOR_DEV",
				"Medium");
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "ACTIVE");
		tasks.completeButtonClick();
		Assert.assertEquals("Task state should be CLOSED", "CLOSED", tasks.stateTask.getText());
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.caseTasks.click();
		Thread.sleep(3000);
		casesPom.verifyTaskTable();
		Thread.sleep(3000);
		casesPom.tableTaskTitle.click();
		Thread.sleep(10000);
		tasks.refreshButtonInTaskList.click();
		Thread.sleep(5000);
		casesPom.verifyAddedTaskInCase("CaseTask", "0", "Samuel Supervisor", "05/20/2016", "Medium", "CLOSED");
		tasks.attachmentLinkClick();
		Thread.sleep(3000);
		tasks.attachmentLinkClick();
		tasks.verifyAttachmentTable();
		tasks.verifyAddingDocumentIfTaskIsClosed();
		casesPom.caseTitleInTasks.click();
		Thread.sleep(5000);
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertEquals("Case title is wrong", "CaseAddTask (IN APPROVAL)", casesPom.caseTitleDraft.getText());
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

}
