package com.armedia.arkcase.uitests.cases;

import java.io.IOException;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.support.PageFactory;

import com.armedia.arkcase.uitests.base.ArkCaseAuthentication;
import com.armedia.arkcase.uitests.base.ArkCaseTestBase;

public class CasePeopleTests extends ArkCaseTestBase {

	CasePage casePom = PageFactory.initElements(driver, CasePage.class);
	CasesPage casesPom = PageFactory.initElements(driver, CasesPage.class);

	@Test
	public void createNewCaseExtortion() throws InterruptedException, IOException {
		// create case type extortion and verify/edit/delete people initiator
		// contact
		// methods

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanExtortion");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeExtortion();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanExtortion", "Extortion");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanExtortion (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.contactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifyContactMethods("Home phone", "1234567", "samuel-acm");
		Thread.sleep(2000);
		casesPom.editContactMethods.click();
		Thread.sleep(4000);
		casesPom.editFirstContactMethodsMobile("00000");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.contactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifyContactMethods("Mobile", "00000", "samuel-acm");
		casesPom.deleteContactMethods.click();
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.contactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifyFirstContactMethodsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanExtortion", "Extortion");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanExtortion (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanExtortion", "Extortion");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseFraud() throws InterruptedException, IOException {

		// create case fraud verif/edit/delete people initiator organization
		// table

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanFraud");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeFraud();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(2000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(2000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanFraud", "Fraud");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanFraud (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.organizationIcon.click();
		Thread.sleep(4000);
		casesPom.verifyOrganizations("Non-profit", "Armedia", "samuel-acm");
		Thread.sleep(2000);
		casesPom.editOrganization.click();
		Thread.sleep(3000);
		casesPom.editOrganizationsTypeGovernment("Arkcase");
		Thread.sleep(6000);
		casesPom.verifyOrganizations("Government", "Arkcase", "samuel-acm");
		driver.navigate().refresh();
		Thread.sleep(8000);
		casesPom.organizationIcon.click();
		Thread.sleep(4000);
		casesPom.verifyOrganizations("Government", "Arkcase", "samuel-acm");
		Thread.sleep(2000);
		casesPom.deleteOrganization.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.organizationIcon.click();
		Thread.sleep(4000);
		casesPom.verifyFirstOrganizationDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanFraud", "Fraud");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanFraud (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanFraud", "Fraud");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseInvestorComplaint() throws InterruptedException, IOException {
		// create case investor complaint verify/edit/delete people initiator
		// address

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanInvestorComplaint");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeInvestorComplaint();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(2000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(2000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanInvestorComplaint", "Investor Complaint");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanInvestorComplaint (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.addressIcon.click();
		Thread.sleep(4000);
		casesPom.verifyAddressesTable("Business", "Second Street", "New York", "New York", "1000", "", "samuel-acm");
		casesPom.editAddress.click();
		Thread.sleep(3000);
		casesPom.verifyEditAddressTitle();
		casesPom.editAddress("101", "Washington", "Washington", "0987", "Washington");
		casesPom.verifyAddressesTable("Home", "101", "Washington", "Washington", "0987", "Washington", "samuel-acm");
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.addressIcon.click();
		Thread.sleep(4000);
		casesPom.verifyAddressesTable("Home", "101", "Washington", "Washington", "0987", "Washington", "samuel-acm");
		casesPom.deleteAddress.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.addressIcon.click();
		Thread.sleep(4000);
		casesPom.verifyAddressDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanInvestorComplaint", "Investor Complaint");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanInvestorComplaint (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanInvestorComplaint", "Investor Complaint");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseLocal() throws InterruptedException, IOException {
		// create case investor complaint add/edit/delete people initiator
		// aliases table

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanLocal");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeLocal();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanLocal", "Local");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanLocal (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.aliasesIcon.click();
		Thread.sleep(4000);
		casesPom.verifyAliasesTable();
		casesPom.addAliasButton.click();
		casesPom.addNewAliasFKA("Tiger");
		casesPom.verifyFirstAddedAlias("FKA", "Tiger", "samuel-acm");
		Thread.sleep(2000);
		casesPom.aliasesIcon.click();
		Thread.sleep(5000);
		casesPom.editAlias.click();
		Thread.sleep(3000);
		casesPom.editAlias("Tiger1");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.aliasesIcon.click();
		Thread.sleep(4000);
		casesPom.verifyFirstAddedAlias("Married", "Tiger1", "samuel-acm");
		casesPom.deleteAlias.click();
		Thread.sleep(3000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.aliasesIcon.click();
		Thread.sleep(3000);
		casesPom.verifyFirstAliasDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanLocal", "Local");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanLocal (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanLocal", "Local");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	public void createNewCasePayOff() throws InterruptedException, IOException {
		// create case type payoff and verify/edit Complaintant section table
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanPayoff");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypePayoff();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPayoff", "Payoff");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanPayoff (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.peopleEditRecordC.click();
		Thread.sleep(3000);
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("milann", "jovanovskii");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.verifyPeopleType("Forensic Scientist", "milann", "jovanovskii");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPayoff", "Payoff");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanPayoff (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPayoff", "Payoff");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	public void createNewCasePollution() throws InterruptedException, IOException {

		// create case type Pollution and verify/edit/delete complaintant
		// organization
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanPollution");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypePollution();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPollution", "Pollution");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanPollution (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondOrganizationIcon.click();
		Thread.sleep(5000);
		casesPom.verifySecondOrganization("Non-profit", "Organization Information", "samuel-acm");
		casesPom.secondeditOrganization.click();
		Thread.sleep(2000);
		casesPom.editOrganizationsTypeGovernment("value");
		Thread.sleep(2000);
		casesPom.verifySecondOrganization("Government", "value", "samuel-acm");
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.secondOrganizationIcon.click();
		Thread.sleep(3000);
		casesPom.verifySecondOrganization("Government", "value", "samuel-acm");
		casesPom.secondDeleteOrganization.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondOrganizationIcon.click();
		Thread.sleep(3000);
		casesPom.verifySecondOrganizationIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPollution", "Pollution");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanPollution (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanPollution", "Pollution");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	public void createNewCaseGovernment() throws InterruptedException, IOException {

		// create case type Pollution and verify/edit/delete complaintant type
		// address
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanGovernment");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeGovernment();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanGovernment", "Government");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanGovernment (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondAddresessIcon.click();
		Thread.sleep(5000);
		casesPom.verifySecondAddressesTable("Business", "Main avenue", "London", "England", "1209", "", "samuel-acm");
		casesPom.secondEditAddress.click();
		casesPom.verifyEditAddressTitle();
		casesPom.editAddress("Lincoln", "Los Angelos", "California", "321", "California");
		casesPom.verifySecondAddressesTable("Home", "Lincoln", "Los Angelos", "California", "321", "California",
				"samuel-acm");
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondAddresessIcon.click();
		Thread.sleep(4000);
		casesPom.verifySecondAddressesTable("Home", "Lincoln", "Los Angelos", "California", "321", "California",
				"samuel-acm");
		casesPom.secondDeleteAddress.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondAddresessIcon.click();
		Thread.sleep(4000);
		casesPom.verifySecondAddressIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanGovernment", "Government");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanGovernment (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanGovernment", "Government");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test

	public void createNewCaseDomesticDispute() throws InterruptedException, IOException {

		// create case type Domestic Dispute and add alias in complaintant
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestMilanDomesticDispute");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeDomesticDispute();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestMilanDomesticDispute", "Domestic Dispute");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanDomesticDispute (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondAliasesIcon.click();
		Thread.sleep(3000);
		casesPom.verifySecondAliasesTable();
		casesPom.addNewAliasButton.click();
		Thread.sleep(3000);
		casesPom.addNewAliasFKA("Dragon");
		Thread.sleep(5000);
		casesPom.secondAliasesIcon.click();
		Thread.sleep(2000);
		casesPom.verifyAddedAlias("FKA", "Dragon", "samuel-acm");
		Thread.sleep(2000);
		casesPom.editAliasButton.click();
		Thread.sleep(3000);
		casesPom.editAlias("Dragon1");
		Thread.sleep(2000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.secondAliasesIcon.click();
		Thread.sleep(2000);
		casesPom.verifyAddedAlias("Married", "Dragon1", "samuel-acm");
		casesPom.deleteAddedAlias.click();
		Thread.sleep(3000);
		driver.navigate().refresh();
		Thread.sleep(8000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondAliasesIcon.click();
		Thread.sleep(3000);
		casesPom.verifySecondAliasDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestMilanDomesticDispute", "Domestic Dispute");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestMilanDomesticDispute (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestMilanDomesticDispute", "Domestic Dispute");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBetterBusinessDispute() throws InterruptedException, IOException {
		// create case type extortion and verify/edit/delete people complaintant
		// contact
		// methods

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBetterBusinessDispute");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBetterBuisnessDispute();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.typeCD.click();
		Thread.sleep(2000);
		casePom.ClickHomePhoneCd();
		Thread.sleep(2000);
		casePom.insertValueCd("1234567");
		Thread.sleep(2000);
		casePom.typeOI.click();
		Thread.sleep(2000);
		casePom.ClickNonProfitOi();
		Thread.sleep(2000);
		casePom.insertNameOi("Armedia");
		Thread.sleep(2000);
		casePom.typeLI.click();
		Thread.sleep(2000);
		casePom.ClickbuisnessLi();
		Thread.sleep(2000);
		casePom.insertAddressLi("Second Street");
		casePom.insertCityLi("New York");
		Thread.sleep(2000);
		casePom.insertStateLi("New York");
		Thread.sleep(2000);
		casePom.insertZipCodeLi("1000");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.typePcomDevice.click();
		Thread.sleep(2000);
		casePom.typePeopleComHomePhone();
		Thread.sleep(2000);
		casePom.insertPeoplComValue("123455");
		Thread.sleep(2000);
		casePom.typePorganization.click();
		Thread.sleep(2000);
		casePom.typePeopleOrganizationNonProfit();
		Thread.sleep(2000);
		casePom.insertPeopleNameOrganizationInformation();
		Thread.sleep(2000);
		casePom.typePLocation.click();
		Thread.sleep(3000);
		casePom.typePeopleLocationBusiness();
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoAddress("Main avenue");
		casePom.insertPeopleLocationInfoCity("London");
		Thread.sleep(2000);
		casePom.insertPeopleLocationInfoState("England");
		Thread.sleep(2000);
		casePom.inssertPeopleLocationInfoZip("1209");
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBetterBusinessDispute", "Better Business Dispute");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBetterBusinessDispute (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondContactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifySecondContactMethods("Home phone", "123455", "samuel-acm");
		Thread.sleep(5000);
		casesPom.secondContactMethodsEditButton.click();
		Thread.sleep(4000);
		casesPom.editSecondContactMethods("facebook");
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.priorityTypePeople();
		casesPom.secondContactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifySecondContactMethods("Facebook", "facebook", "samuel-acm");
		casesPom.secondContactMethodsDeleteButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.priorityTypePeople();
		Thread.sleep(3000);
		casesPom.secondContactMethodIcon.click();
		Thread.sleep(4000);
		casesPom.verifySecondContactMethodIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBetterBusinessDispute", "Better Business Dispute");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBetterBusinessDispute (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBetterBusinessDispute", "Better Business Dispute");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddDeletePerson() throws InterruptedException, IOException {
		// create case type Background Investigation add/delete person

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		Thread.sleep(2000);
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(6000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyIfPersonIsAdded();
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdDeletePeopleButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		casesPom.verifyIfAddedPersonIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddEditPerson() throws InterruptedException, IOException {
		// create case type Background Investigation add/edit person

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		Thread.sleep(2000);
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyIfPersonIsAdded();
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdEditPeopleButton.click();
		Thread.sleep(4000);
		casesPom.addPersonTypeVictim("milann", "jovanovskii");
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		casesPom.verifyAddedPerson("Forensic Scientist", "milann", "jovanovskii");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonAddContactMethods()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, add contact
		// methods

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		Thread.sleep(2000);
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyIfPersonIsAdded();
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdContactMethodsIcon.click();
		Thread.sleep(3000);
		casesPom.thirdContactMethodAddButton.click();
		Thread.sleep(3000);
		casesPom.addContactMethodsMobile("00000");
		Thread.sleep(3000);
		casesPom.thirdContactMethodsIcon.click();
		Thread.sleep(2000);
		casesPom.verifyAdedThirdContactMethod("Mobile", "00000", "samuel-acm");
		casesPom.thirdContactMethodDeleteButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		casesPom.thirdContactMethodsIcon.click();
		Thread.sleep(4000);
		casesPom.verifyThirdContactMethodIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonAddDeleteOrganization()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, add/delete
		// organization

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		Thread.sleep(2000);
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyIfPersonIsAdded();
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdOrganizationsIcon.click();
		Thread.sleep(3000);
		casesPom.thirdOrganizationAddButton.click();
		Thread.sleep(3000);
		casesPom.addOrganization("org");
		Thread.sleep(3000);
		casesPom.thirdOrganizationsIcon.click();
		Thread.sleep(3000);
		casesPom.verifyThirdAddedOrganization("Government", "org", "samuel-acm");
		casesPom.thirdOrganizationDeleteButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		casesPom.thirdOrganizationsIcon.click();
		Thread.sleep(4000);
		casesPom.verifyThirdAddedOrganizationIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonAddDeleteAddress()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, add/delete
		// address

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		Thread.sleep(2000);
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.verifyIfPersonIsAdded();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdAddressIcon.click();
		Thread.sleep(3000);
		casesPom.thirdAddressAddButton.click();
		Thread.sleep(3000);
		casesPom.addAddress("first st.", "skopje", "macedonia", "1000", "macedonia");
		Thread.sleep(3000);
		casesPom.thirdAddressIcon.click();
		Thread.sleep(3000);
		casesPom.verifyThirdAddedAddress("Home", "first st.", "skopje", "macedonia", "1000", "macedonia", "samuel-acm");
		casesPom.thirdAddedAddressDeleteButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		casesPom.thirdAddressIcon.click();
		Thread.sleep(4000);
		casesPom.verifyThirdAddedAddressIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonAddDeleteAlias() throws InterruptedException, IOException {
		// create case type Background Investigation add person, add/delete
		// alias

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (DRAFT)"));
		Thread.sleep(4000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.peopleAddNewButton.click();
		Thread.sleep(3000);
		casesPom.verifyAddPersonTitle();
		casesPom.verifyPersonTypes();
		casesPom.addPersonType("Milan", "Jovanovski");
		Thread.sleep(3000);
		casesPom.verifyIfPersonIsAdded();
		casesPom.verifyAddedPerson("Forensic Scientist", "Milan", "Jovanovski");
		casesPom.thirdAliasesIcon.click();
		Thread.sleep(8000);
		casesPom.thirdAliasAddButton.click();
		Thread.sleep(3000);
		casesPom.addNewAliasFKA("shorty");
		Thread.sleep(3000);
		casesPom.thirdAliasesIcon.click();
		Thread.sleep(6000);
		casesPom.verifyThirdAddedAlias("FKA", "shorty", "samuel-acm");
		Thread.sleep(3000);
		casesPom.thirdAliasDeleteButton.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		casesPom.casePeople.click();
		Thread.sleep(3000);
		casesPom.thirdAliasesIcon.click();
		Thread.sleep(3000);
		casesPom.verifyThirdAddedAliasesIsDeleted();
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonCheckTypeFilter()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, check the type/
		// filters

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseTestBackgroundInvestigation (DRAFT)",
				casesPom.caseTitleDraft.getText());
		casesPom.casePeople.click();
		Thread.sleep(4000);
		casesPom.priorityTypePeople();
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.checkPeopleTypeFilter("aaa");
		Thread.sleep(4000);
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonCheckFirstNameFilter()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, check the first
		// name filter

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseTestBackgroundInvestigation (DRAFT)",
				casesPom.caseTitleDraft.getText());
		casesPom.casePeople.click();
		Thread.sleep(4000);
		casesPom.priorityTypePeople();
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.checkPeopleFirstNameFilter("bbb");
		Thread.sleep(4000);
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test
	public void createNewCaseBackgroundInvestigationAddPersonCheckLastNameFilter()
			throws InterruptedException, IOException {
		// create case type Background Investigation add person, check the first
		// name filter

		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(casesPom.frameOne);
		driver.switchTo().frame(casesPom.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("CaseTestBackgroundInvestigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		Thread.sleep(2000);
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyPeopleTab();
		casePom.titlePeople.click();
		Thread.sleep(2000);
		casePom.clickTitlePeopleMr();
		Thread.sleep(2000);
		casePom.insertFirstNamePeople("Milan");
		casePom.insertLastNamePeople("Jovanovski");
		Thread.sleep(2000);
		casePom.typePeopleInfo.click();
		Thread.sleep(2000);
		casePom.typePeopleComplaintant();
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(8000);
		driver.switchTo().defaultContent();
		Thread.sleep(4000);
		casesPom.verifyCreatedCaseInfo("CaseTestBackgroundInvestigation", "Background Investigation");
		casesPom.VerifycreatedDate();
		Assert.assertEquals("Case title is wrong", "CaseTestBackgroundInvestigation (DRAFT)",
				casesPom.caseTitleDraft.getText());
		casesPom.casePeople.click();
		Thread.sleep(4000);
		casesPom.priorityTypePeople();
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.checkPeopleLastNameFilter("ccc");
		Thread.sleep(4000);
		casesPom.verifyPeopleSectionInitiator("Milan", "Jovanovski");
		casesPom.verifyPeopleType("Complaintant", "Milan", "Jovanovski");
		casesPom.changeCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(casesPom.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(casesPom.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		casesPom.deleteCase();
		driver.switchTo().defaultContent();
		casesPom.refreshPage.click();
		Thread.sleep(3000);
		Assert.assertTrue(casesPom.caseTitleDraft.getText().equals("CaseTestBackgroundInvestigation (IN APPROVAL)"));
		casesPom.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

}
