<script src="<%= request.getContextPath()%>/lib/jquery/dist/jquery.js"></script>
<script src="<%= request.getContextPath()%>/lib/jquery-ui/jquery-ui.js"></script>
<script src="<%= request.getContextPath()%>/lib/fancytree/dist/jquery.fancytree.js"></script>
<script src="<%= request.getContextPath()%>/lib/tv4/tv4.js"></script>
<script src="<%= request.getContextPath()%>/lib/objectpath/lib/ObjectPath.js"></script>
<script src="<%= request.getContextPath()%>/lib/lodash/lodash.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular/angular.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-resource/angular-resource.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-cookies/angular-cookies.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-animate/angular-animate.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-touch/angular-touch.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-sanitize/angular-sanitize.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-ui-router/release/angular-ui-router.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-ui-grid/ui-grid.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-schema-form/dist/schema-form.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-schema-form/dist/bootstrap-decorator.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-translate/angular-translate.js"></script>
<script src="<%= request.getContextPath()%>/lib/angular-translate-loader-partial/angular-translate-loader-partial.j"></script>