package com.armedia.arkcase.uitests.cases.documents;

import java.io.IOException;

import org.junit.Test;
import org.openqa.selenium.support.PageFactory;

import com.armedia.arkcase.uitests.base.ArkCaseAuthentication;
import com.armedia.arkcase.uitests.base.ArkCaseTestBase;
import com.armedia.arkcase.uitests.base.ArkCaseTestUtils;
import com.armedia.arkcase.uitests.cases.CasePage;
import com.armedia.arkcase.uitests.cases.CasesPage;

public class CaseDocumentsTest extends ArkCaseTestBase {

	CasesPage cases = PageFactory.initElements(driver, CasesPage.class);
	CasePage casePom = PageFactory.initElements(driver, CasePage.class);
	CaseDocumentsPage documentsPage = PageFactory.initElements(driver, CaseDocumentsPage.class);
	ArkCaseTestUtils utils = new ArkCaseTestUtils();

	@Test
	public void createNewCaseVerifyDocumentsSection() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Documents");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(4000);
		documentsPage.verifyDocumentsTable();
		documentsPage.clickRootExpander();
		Thread.sleep(3000);
		documentsPage.verifyFirstDocument("ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@Test

	public void createNewCaseAddDocumentFromFrevvoVerify() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Documents");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(3000);
		casePom.attachmentsAddFilesClickButton();
		Thread.sleep(2000);
		casePom.browseButtonClick();
		casePom.addFile();
		Thread.sleep(3000);
		casePom.upploadButtonClick();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		Thread.sleep(2000);
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(4000);
		documentsPage.verifyDocumentsTable();
		documentsPage.clickRootExpander();
		Thread.sleep(3000);
		documentsPage.verifySecondDocument("caseSummary.pdf", "Attachment", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddNewDocumentOther() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("caseother");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(6000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(3000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(3000);
		documentsPage.verifyDocumentOtherName();
		Thread.sleep(5000);
		documentsPage.clickDocumentOther();
		utils.uploadPicture();
		Thread.sleep(5000);
		documentsPage.verifySecondDocument("imageprofile.png", "Other", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddNewdocumentWitnessInterview() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Witnes Interview");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(4000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifydocumentWitnessInterviewName();
		documentsPage.clickDocumentWitnessInterview();
		utils.uploadPdf();
		Thread.sleep(5000);
		documentsPage.verifySecondDocument("caseSummary.pdf", "Witness Interview Request", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddNewdocumentNoticeOfInvestigation() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Notice of Investigation");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifyDocumentNoticeOfInvestigationName();
		documentsPage.clickDocumentNoticeOfInvestigation();
		utils.uploadDocx();
		Thread.sleep(8000);
		documentsPage.verifySecondDocument("ArkCaseTesting.docx", "Notice Of Investigation", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);
	}

	@Test
	@SuppressWarnings("static-access")
	public void createNewCaseAddDocumentSF86Signature() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("SF86Signature");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifyDocumentSF86Signature();
		documentsPage.clickDocumentSF86Signature();
		utils.uploadXlsx();
		Thread.sleep(8000);
		documentsPage.verifySecondDocument("caseSummary.xlsx", "Sf86 Signature", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddDocumentEDelivery() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Edelivery");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifyDocumentEDelivery();
		documentsPage.clickDocumentEDelivery();
		utils.uploadPicture();
		Thread.sleep(8000);
		documentsPage.verifySecondDocument("imageprofile.png", "Edelivery", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddDocumentGeneralRelease() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("General Release");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifyDocumentGeneralRelease();
		documentsPage.clickDocumentGeneralRelease();
		utils.uploadDocx();
		Thread.sleep(10000);
		documentsPage.verifySecondDocument("ArkCaseTesting.docx", "General Release", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}

	@SuppressWarnings("static-access")
	@Test
	public void createNewCaseAddDocumentMedicalRelease() throws InterruptedException, IOException {

		ArkCaseAuthentication.logIn("samuel-acm", "Armedia#1", driver, baseUrl);
		casePom.newCase();
		Thread.sleep(20000);
		driver.switchTo().frame(cases.frameOne);
		driver.switchTo().frame(cases.frameTwo);
		casePom.vrifyGeneralInformationTabName();
		casePom.caseTitleInput("Medical Release");
		casePom.verifyCaseTypeTitle();
		casePom.caseTypeInputClick();
		Thread.sleep(2000);
		casePom.caseTypeBackgroundInvestigation();
		Thread.sleep(2000);
		casePom.nextButton.click();
		Thread.sleep(3000);
		casePom.verifyInitiatorTab();
		casePom.initiatorTitle.click();
		Thread.sleep(2000);
		casePom.clickInitiatorMr();
		Thread.sleep(2000);
		casePom.initiatorFirstName("Milan");
		casePom.initiatorLastName("Jovanovski");
		Thread.sleep(2000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.nextButtonClick();
		Thread.sleep(3000);
		casePom.verifyAttachmentTab();
		Thread.sleep(2000);
		casePom.participantnsTab.click();
		Thread.sleep(2000);
		casePom.selectParticipantTypeClick();
		Thread.sleep(2000);
		casePom.selectparticipantOwner();
		casePom.selectParticipantClick();
		Thread.sleep(3000);
		casePom.searchForUsers();
		Thread.sleep(3000);
		casePom.searchedName();
		casePom.addSearchedNameClick();
		Thread.sleep(2000);
		casePom.submit.click();
		Thread.sleep(10000);
		driver.switchTo().defaultContent();
		cases.caseDocuments.click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(10000);
		documentsPage.performRightClickOnRoot();
		Thread.sleep(4000);
		documentsPage.checkIfRightClickOnRootIsWorking();
		Thread.sleep(3000);
		documentsPage.verifyNewDocmentName();
		documentsPage.newDocumentClick();
		Thread.sleep(4000);
		documentsPage.verifyDocumentMedicalRelease();
		documentsPage.clickDocumentMedicalRelease();
		utils.uploadXlsx();
		Thread.sleep(10000);
		documentsPage.verifySecondDocument("caseSummary.xlsx", "Medical Release", "1.0", "ACTIVE");
		documentsPage.chnageCaseStatusButton.click();
		Thread.sleep(10000);
		driver.switchTo().frame(cases.chnageCaseStausFrameOne);
		Thread.sleep(2000);
		driver.switchTo().frame(cases.chnageCaseStatusFrameTwo);
		Thread.sleep(2000);
		cases.deleteCase();
		driver.switchTo().defaultContent();
		cases.changeCaseStatusAproved();
		Thread.sleep(3000);
		ArkCaseAuthentication.logOut(driver);

	}
}
