'use strict';

ApplicationConfiguration.registerModule('dashboard', [
    'adf',
    'adf.provider',
    'chart.js',
    'dashboard.cases-by-queue',
    'dashboard.cases-by-status',
    'dashboard.my-cases',
    'dashboard.my-complaints',
    'dashboard.my-tasks',
    'dashboard.new-complaints',
    'dashboard.team-workload',
    'dashboard.weather',
    'dashboard.news',
    'dashboard.details',
    'dashboard.locations',
    'dashboard.people',
    'dashboard.documents',
    'dashboard.participants',
    'dashboard.reworkDetails',
    'dashboard.docReview',
    'dashboard.notes',
    'dashboard.tasks',
    'dashboard.references',
    'dashboard.workflow',
    'dashboard.history',
    'dashboard.correspondence',
    'dashboard.time',
    'dashboard.cost',
    'dashboard.calendar',
    'dashboard.signature',
    'dashboard.person',
    'dashboard.expenses',
    'dashboard.hoursSummary',
    'dashboard.new-cases'
]);